name: Test and Coverage

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  build:
    name: Build, Test and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache do Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - run: chmod +x gradlew

      - name: Test + Coverage
        run: ./gradlew test jacocoCoverageVerification

